version: '3.1'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres #Do not change this value
      POSTGRES_USER: postgres #Do not change this value
      POSTGRES_PASSWORD: password #Do not change this value
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "8082:5432" #Change the port 8082 if it is aldready being use

  web:
    build: .
    ports:
      - "8083:5000" #Change the Port 8083 if port 5432 is aldready being used.
    volumes:
      - .:/app
    depends_on:
      - db #Do not change this value

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: username@mail.com #Do not change this value
      PGADMIN_DEFAULT_PASSWORD: password  #Do not change this value
    ports:
      - "8081:80" #Change the Port 8081 if aldready being used.
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  postgres_data:
  pgadmin_data:
