version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - query-craft_postgres_data:/var/lib/postgresql/data
    ports:
      - "8082:5432" #Change the Port 8082 if aldready beimg used.

  web:
    image: query-craft-web
    ports:
      - "8083:5000"
    depends_on:
      - db

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80" #Change the Port 8082 if aldready beimg used.
    volumes:
      - query-craft_pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  query-craft_postgres_data:
    external: true
  query-craft_pgadmin_data:
    external: true
